export const categories = [
  'National News', 'International News', 'Politics', 'Business', 'Technology',
  'Sports', 'Entertainment', 'Health', 'Science', 'Education', 'Lifestyle',
  'Environment', 'Crime', 'Opinion', 'Regional News', 'Economy', 'World Events',
  'Society and Culture', 'Law', 'Finance', 'Technology and Innovation', 'Arts',
  'Travel', 'Food', 'Fashion', 'Real Estate', 'Personal Finance', 'Startups',
  'Cybersecurity', 'Social Media', 'Automotive', 'Space Exploration', 'Mental Health',
  'Human Rights', 'Public Health', 'Elections', 'Government Policies', 'Social Movements',
  'Wildlife', 'Conservation', 'Pandemics', 'Consumer Electronics', 'Artificial Intelligence',
  'Gaming', 'Theater', 'Music Industry', 'Celebrities', 'Military', 'Diplomacy', 'Weather',
  'Natural Disasters', 'Philanthropy', 'Agriculture', 'Transportation', 'Infrastructure',
  'Energy', 'Mining', 'Telecommunications', 'Biotechnology', 'Pharmaceuticals', 'Aviation',
  'Maritime', 'Retail', 'Hospitality', 'Media', 'Publishing', 'Education Policy',
  'Space Technology', 'Robotics', 'Cryptocurrency', 'Virtual Reality', 'Augmented Reality',
  'Fitness', 'Wellness', 'Parenting', 'Sustainability', 'Urban Development', 'Rural Development',
  'Artificial Intelligence Ethics', 'Big Data', 'Nanotechnology', 'Climate Action', 'Renewable Energy',
  'Smart Cities', 'E-commerce', 'Luxury Goods', 'Art Market', 'Antiques', 'Cultural Heritage',
  'Historical Events', 'Language and Linguistics', 'Philosophy', 'Religious Studies', 'Architecture',
  'Urban Planning', 'Public Transportation', 'Oceanography', 'Meteorology', 'Astrobiology', 'Genetics',
  'Stem Cell Research', 'Quantum Computing', 'Ethics and Morality', 'Global Health', 'Vaccines',
  'Medical Devices', 'Elder Care', 'Disability Rights', 'Diversity and Inclusion', 'Immigration',
  'Refugee Crises', 'Peacekeeping', 'Space Missions', 'Astronomy', 'Exploration', 'Artificial Life'
];
